name: CI CD Non-Prod

on:
  push:
    branches:
      - master
      - main

jobs:
  get_vars:
    name: Expose variables
    uses: ./.github/workflows/1-vars.yml
    with:
      ENVIRONMENT: production

  deploy:
    name: Deploy Production
    needs: get_vars
    uses: ./.github/workflows/1-deploy.yml
    with:
      ENVIRONMENT: production
      SSH_HOST: ${{ needs.get_vars.outputs.DEPLOY_TO }}
      FOLDER_PATH: ${{ needs.get_vars.outputs.FOLDER_PATH }}
      UTILS_HOST: ${{ secrets.UTILS_HOST }}
    secrets: inherit

  notify:
    name: Notify on Slack
    if: always()
    needs: deploy
    uses: ./.github/workflows/slack-event.yml
    with:
      ENVIRONMENT: production
      SLACK_CHANNEL_ID: bobrov-test
      STATUS: ${{ needs.deploy-production.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
