name: CI CD Non-Prod

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        default: 'dev'
        description: 'Environment name'
        required: true
        options:
          - alpha
          - staging
          - dev

jobs:
  get_vars:
    name: Expose variables
    uses: ./.github/workflows/1-vars.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

  deploy:
    name: Deploy non-production
    needs: get_vars
    uses: ./.github/workflows/1-deploy.yml
    if: ${{ inputs.ENVIRONMENT != 'production' }}
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      SSH_HOST: ${{ needs.get_vars.outputs.DEPLOY_TO }}
      FOLDER_PATH: ${{ needs.get_vars.outputs.FOLDER_PATH }}
    secrets: inherit

  notify:
    name: Notify on Slack
    if: always()
    needs: deploy-production
    uses: ./.github/workflows/slack-event.yml
    with:
      ENVIRONMENT: ${{ env.ENVIRONMENT }}
      SLACK_CHANNEL_ID: bobrov-test
      STATUS: ${{ needs.deploy-production.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}