name: CI CD Non-Prod

on:
  push:
    branches:
      - master
      - main

jobs:
  get_vars:
    name: Expose variables
    uses: ./.github/workflows/1-vars.yml
    with:
      ENVIRONMENT: production

  deploy_1:
    name: Deploy Production in Platform
    needs: get_vars
    uses: ./.github/workflows/1-deploy.yml
    with:
      ENVIRONMENT: production
      SSH_HOST: ${{ needs.get_vars.outputs.DEPLOY_TO_1 }}
      FOLDER_PATH: ${{ needs.get_vars.outputs.FOLDER_PATH }}
    secrets: inherit

  deploy_2:
    name: Deploy Production in Utils
    needs: [get_vars, deploy_1]
    uses: ./.github/workflows/1-deploy.yml
    with:
      ENVIRONMENT: production
      SSH_HOST: ${{ needs.get_vars.outputs.DEPLOY_TO_2 }}
      FOLDER_PATH: ${{ needs.get_vars.outputs.FOLDER_PATH }}
    secrets: inherit

  notify:
    name: Notify on Slack
    if: always()
    needs: [deploy_1, deploy_2]
    uses: ./.github/workflows/slack-event.yml
    with:
      ENVIRONMENT: production
      SLACK_CHANNEL_ID: bobrov-test
      STATUS: ${{ needs.deploy_2.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
