name: Check membership

on:
  workflow_call:
    outputs:
      IS_TEAM_MEMBER:
        description: "SSH host to deploy backend to"
        value: ${{ jobs.check_membership.outputs.isTeamMember }}

jobs:
  check_membership:
    environment: ${{ inputs.ENVIRONMENT }}

    runs-on: ubuntu-latest

    outputs:
      isTeamMember: ${{ steps.check-membership.outputs.isTeamMember }}

    steps:
      - uses: tspascoal/get-user-teams-membership@v1
        id: check-membership
        with:
          username: ${{ github.actor }}
          team: 'front-end-deploy'
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - run: echo "${{ steps.check-membership.outputs.isTeamMember }}"
