name: ci_build

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Infrastructure environment name to build and deploy the artifacts to'
        required: true
        type: string
      NODE_ENV:
        description: 'App environment name to set appropriate settings for build'
        required: true
        type: string
      NPM_CONFIG_PRODUCTION:
        description: 'NPM_CONFIG_PRODUCTION environment variable'
        required: true
        type: string

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
  NODE_ENV: ${{ inputs.NODE_ENV }}
  NODE_OPTIONS: '--max-old-space-size=4096'
  NPM_CONFIG_PRODUCTION: ${{ inputs.NPM_CONFIG_PRODUCTION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          check-latest: true

      - run: node -v

      - run: yarn -v

