name: Push notification to Slack v2

on:
  workflow_dispatch:

jobs:
  send_event:
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.ALB_SLACK_WEBHOOK_URL }}
          payload: |
            "text": "{{ github.workflow }} build result: ${{ inputs.STATUS }}"
            "blocks":
              - type: "header"
                text:
                  type: "plain_text"
                  text: "${{ github.workflow }} build result: inputs-STATUS"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Repository:* ${{ github.repository }}"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Branch:*\n${{ github.ref_name }}"
                  - type: "mrkdwn"
                    text: "*Status:*\ninputs.STATUS"
              - type: "section"
                block_id: "section789"
                fields:
                  - type: "mrkdwn"
                    text: "*Average Rating*\\n1.0"
                  - type: "mrkdwn"
                    text: "*Average Rating*\\n2.0"
