name: CI > Workflow > Push notification on Slack

on:
  workflow_dispatch:

jobs:
  send_event:
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.ALB_SLACK_WEBHOOK_URL }}
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "${{ github.workflow }} build result: inputs-STATUS"
              - type: "section"
            	  fields:
            	    type: "mrkdwn"
            	    text: "*Repository:*\n${{ github.repository }}"
