name: CI > Workflow > Push notification on Slack

on:
  workflow_dispatch:

jobs:
  send_event:
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: webhook-trigger
          webhook: ${{ secrets.ALB_SLACK_WEBHOOK_URL }}
          payload-file-path: "./payload.yml"
