name: Push notification to Slack v2

on:
  workflow_dispatch:

jobs:
  send_event:
    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.ALB_SLACK_WEBHOOK_URL }}
          payload: |
            "text": "Danny Torrence left a 1 star review for your property."
            "blocks":
              - type: "header"
                text:
                  type: "plain_text"
                  text: "${{ github.workflow }} build result: inputs-STATUS"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Danny Torrence left the following review for your property:"
              - type: "section"
                block_id: "section567"
                text:
                  type: "mrkdwn"
                  text: "<https://example.com|Overlook Hotel> \\n :star: \\n Doors had too many axe holes, guest in room 237 was far too rowdy, whole place felt stuck in the 1920s."
              - type: "section"
                block_id: "section789"
                fields:
                  - type: "mrkdwn"
                    text: "*Average Rating*\\n1.0"
