name: Push notification on Slack

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment name'
        required: true
        type: string
      SLACK_CHANNEL_ID:
        description: 'Slack channel ID where message will be posted'
        required: true
        type: string
      STATUS:
        description: 'The result of a deployment job'
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: 'Slack webhook URL'
        required: true

jobs:
  send_event:

    runs-on: ubuntu-latest

    steps:
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: ${{ inputs.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "repository": "${{ github.repository }}",
              "environment": "${{ inputs.ENVIRONMENT }}",
              "branch": "${{ github.ref_name }}",
              "status": "${{ inputs.STATUS }}",
              "user": "${{ github.actor }}",
              "commit_hash": "${{ github.sha }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
